#12.5.0 old version, downgrading to Python 11 for snowpark to work
FROM quay.io/astronomer/astro-runtime:11.15.1
RUN mkdir -p /home/astro/.dbt
COPY profiles.yml /home/astro/.dbt/profiles.yml
ENV AIRFLOW__RESOURCES__MEMORY_LIMIT=3g
ENV AIRFLOW__RESOURCES__MEMORY_RESERVATION=2g
#ENV AIRFLOW__SCHEDULER__PARSING_PROCESSES=1
#ENV AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=60
#ENV AIRFLOW__WEBSERVER__WORKERS=1
#ENV AIRFLOW__WEBSERVER__WORKER_CLASS=sync
#ENV AIRFLOW__WEBSERVER__WORKER_TIMEOUT=120
#ENV AIRFLOW__CELERY__WORKER_CONCURRENCY=1